param(
    [Parameter(Mandatory = $true)][ValidateSet("arcade", "puzzle", "defense")][string]$Template,
    [Parameter(Mandatory = $true)][string]$Codename,
    [string]$DisplayName = "",
    [string]$AndroidApplicationId = "",
    [string]$IOSBundleId = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Ensure-CorePackageManifestPath([string]$UnityProjectPath, [string]$RepoRoot) {
    $manifestPath = Join-Path $UnityProjectPath "Packages/manifest.json"
    if (!(Test-Path $manifestPath)) {
        throw "manifest.json not found: $manifestPath"
    }

    $manifestObj = Get-Content -Path $manifestPath -Raw | ConvertFrom-Json
    $deps = [ordered]@{}
    $manifestObj.dependencies.PSObject.Properties | ForEach-Object { $deps[$_.Name] = $_.Value }

    $manifestDir = Split-Path -Parent $manifestPath
    $coreAbsPath = [System.IO.Path]::GetFullPath((Join-Path $RepoRoot "Packages/MiniLab.Core"))
    $coreRelative = [System.IO.Path]::GetRelativePath($manifestDir, $coreAbsPath).Replace('\', '/')
    $deps["com.zebratank.minilab.core"] = "file:$coreRelative"

    $manifestOut = [ordered]@{
        dependencies = $deps
    }
    if ($manifestObj.PSObject.Properties.Name -contains "scopedRegistries") {
        $manifestOut["scopedRegistries"] = $manifestObj.scopedRegistries
    }

    $manifestOut | ConvertTo-Json -Depth 20 | Set-Content -Path $manifestPath
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$templateTitle = (Get-Culture).TextInfo.ToTitleCase($Template)
$templatePath = Join-Path $repoRoot ("Templates/{0}Template" -f $templateTitle)
if (!(Test-Path $templatePath)) {
    throw "Template not found: $templatePath"
}

$unityTemplatePath = Join-Path $templatePath "UnityProject"
if (!(Test-Path $unityTemplatePath)) {
    throw "Template Unity project not found. Run tools/bootstrap-template-projects.ps1 first."
}

$gameName = "Game_{0}_{1}" -f $templateTitle, $Codename
$gamePath = Join-Path $repoRoot ("Games/{0}" -f $gameName)
if (!(Test-Path $gamePath)) {
    New-Item -ItemType Directory -Path $gamePath -Force | Out-Null
    Write-Host "Created game folder: $gamePath"
} else {
    Write-Host "Game folder already exists, reusing: $gamePath"
}

$gameReadme = Join-Path $gamePath "README.md"
if (!(Test-Path $gameReadme)) {
    Copy-Item (Join-Path $templatePath "README.md") $gameReadme -Force
}

$gameUnityProject = Join-Path $gamePath "UnityProject"
if (Test-Path $gameUnityProject) {
    Write-Host "UnityProject already exists -> skip copy (Library cache preserved)."
} else {
    Copy-Item $unityTemplatePath $gameUnityProject -Recurse -Force
    Write-Host "UnityProject copied from template."
}

Ensure-CorePackageManifestPath -UnityProjectPath $gameUnityProject -RepoRoot $repoRoot
Write-Host "Core package manifest path normalized."

if ([string]::IsNullOrWhiteSpace($DisplayName)) {
    $DisplayName = $Codename
}

$slug = ($Codename -replace '[^A-Za-z0-9]', '').ToLowerInvariant()
if ([string]::IsNullOrWhiteSpace($slug)) {
    $slug = "minigame"
}

if ([string]::IsNullOrWhiteSpace($AndroidApplicationId)) {
    $AndroidApplicationId = "com.zebratank.$slug"
}

if ([string]::IsNullOrWhiteSpace($IOSBundleId)) {
    $IOSBundleId = $AndroidApplicationId
}

$storeYamlPath = Join-Path $gamePath "store.yaml"
if (Test-Path $storeYamlPath) {
    Write-Host "store.yaml already exists -> skip overwrite."
} else {
@"
game_code: "$($Template)_$slug"
bundle_id_ios: "$IOSBundleId"
application_id_android: "$AndroidApplicationId"

locales:
  tr-TR:
    app_name: "$DisplayName"
    short_description: "MiniLab mini oyun"
    long_description: "MiniLab Factory tarafindan olusturulan $DisplayName mini oyunu."
    ad_text: "Odullu reklam metni"
  en-US:
    app_name: "$DisplayName"
    short_description: "MiniLab mini game"
    long_description: "$DisplayName mini game generated by MiniLab Factory."
    ad_text: "Rewarded ad copy"

category:
  android: "$templateTitle"
  ios: "Games/$templateTitle"

tags:
  - "$Template"
  - "minilab"

privacy_policy_url: "https://example.com/privacy"
support_email: "support@zebratank.com"

sdk_inventory:
  core:
    - "AdMob SDK"
    - "Google UMP SDK"
  delta:
    - "none"

release_notes_template:
  tr-TR:
    - "Ilk surum"
  en-US:
    - "Initial release"

shots_ref:
  screenshot_shot_list: "Docs/assets/shots/default_screens.md"
  video_shot_list: "Docs/assets/shots/default_video.md"
"@ | Set-Content -Path $storeYamlPath
}

Write-Host "Created game: $gameName"
Write-Host "Game path: $gamePath"
Write-Host "Unity project: $gamePath\\UnityProject"
Write-Host "store.yaml: $storeYamlPath"
